{
 "title": "Power Meter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "Lokasjon",
    "query": "label_values(kaifa_info, location)"
   }
  ]
 },
 "panels": [
  {
   "title": "Forbruk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "kaifa_active_power_imported_watts{location=\"$location\"}"
    }
   ]
  },
  {
   "title": "Meterstand",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kaifa_cumulative_active_import_energy_watt_hours{location=\"$location\"} / 1000"
    }
   ]
  },
  {
   "title": "L1/L2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "kaifa_voltage{phase=\"L1-L2\"}"
    }
   ]
  },
  {
   "title": "L2/L3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "kaifa_voltage{phase=\"L2-L3\"}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "targets": [
    { "expr": "kaifa_info" }
   ]
  },
  {
   "title": "Total reaktiv effekt",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kaifa_cumulative_reactive_import_energy_var_hours{location=\"$location\"} / 1000"
    }
   ]
  },
  {
   "title": "Forbruk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "kaifa_active_power_imported_watts"
    }
   ]
  },
  {
   "title": "Strøm",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "kaifa_current{phase!=\"L2\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Reaktiv effekt",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "voltampreact" }
   ],
   "targets": [
    {
     "expr": "kaifa_reactive_power_imported_var",
     "legendFormat": "import"
    },
    {
     "expr": "-kaifa_reactive_power_exported_var",
     "legendFormat": "eksport"
    }
   ]
  }
 ]
}